# Generated by Django 3.0.7 on 2020-06-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='email',
            field=models.EmailField(default='NA', max_length=254),
        ),
    ]
